export enum StatusEnum {
  未开始 = 1,
  进行中,
  成功,
  失败,
}
export enum NodeEnum {
  阶段 = 1,
  版本,
  开发,
  集成,
  验证,
  发布,
}

export const mockData = [
  {
    pSVPlanId: 0,
    cooldevProjectId: 0,
    projectSureStageId: 'E245.DV',
    planVersion: 'E245.DV.01.01dddddd',
    planStageList: [
      {
        stageName: '开发',
        sort: 0,
        status: StatusEnum.成功,
        startTime: '2024-06-05 18:30:21',
        endTime: '2024-06-10 14:30:50',
      },
      {
        stageName: '集成',
        sort: 1,
        status: StatusEnum.成功,
        startTime: '2024-06-05 18:30:21',
        endTime: '2024-06-10 14:30:50',
      },
      {
        stageName: '版本验证',
        sort: 2,
        status: StatusEnum.成功,
        startTime: '2024-06-05 18:30:21',
        endTime: '2024-06-10 14:30:50',
      },
      // {
      //   stageName: '版本发布',
      //   sort: 3,
      //   status: StatusEnum.成功,
      //   startTime: '2024-06-05 18:30:21',
      //   endTime: '2024-06-10 14:30:50',
      // },
    ],
    planCompileList: [
      {
        version: 'E245.DV.01.01.001',
        stageList: [
          {
            id: 1,
            stageKey: '',
            stageName: '集成',
            sort: 0,
            status: StatusEnum.成功,
          },
          {
            id: 2,
            stageKey: '',
            stageName: '转测评估',
            sort: 1,
            status: StatusEnum.成功,
          },
          {
            id: 3,
            stageKey: '',
            stageName: '系统测试',
            sort: 0,
            status: StatusEnum.成功,
          },
          // {
          //   id: 4,
          //   stageKey: '',
          //   stageName: '内部发布',
          //   sort: 0,
          //   status: StatusEnum.成功,
          // },
          // {
          //   id: 5,
          //   stageKey: '',
          //   stageName: '外部发布',
          //   sort: 0,
          //   status: StatusEnum.成功,
          // },
        ],
      },
      {
        version: 'E245.DV.01.01.002',
        stageList: [
          {
            id: 1,
            stageKey: '',
            stageName: '集成',
            sort: 0,
            status: StatusEnum.成功,
          },
          {
            id: 2,
            stageKey: '',
            stageName: '转测评估',
            sort: 1,
            status: StatusEnum.成功,
          },
          {
            id: 3,
            stageKey: '',
            stageName: '系统测试',
            sort: 0,
            status: StatusEnum.成功,
          },
          // {
          //   id: 4,
          //   stageKey: '',
          //   stageName: '内部发布',
          //   sort: 0,
          //   status: StatusEnum.成功,
          // },
          // {
          //   id: 5,
          //   stageKey: '',
          //   stageName: '外部发布',
          //   sort: 0,
          //   status: StatusEnum.成功,
          // },
        ],
      },
      {
        version: 'E245.DV.01.01.003',
        stageList: [
          {
            id: 1,
            stageKey: '',
            stageName: '集成',
            sort: 0,
            status: StatusEnum.成功,
          },
          {
            id: 2,
            stageKey: '',
            stageName: '转测评估',
            sort: 1,
            status: StatusEnum.成功,
          },
          {
            id: 3,
            stageKey: '',
            stageName: '系统测试',
            sort: 0,
            status: StatusEnum.成功,
          },
          // {
          //   id: 4,
          //   stageKey: '',
          //   stageName: '内部发布',
          //   sort: 0,
          //   status: StatusEnum.成功,
          // },
          // {
          //   id: 5,
          //   stageKey: '',
          //   stageName: '外部发布',
          //   sort: 0,
          //   status: StatusEnum.成功,
          // },
        ],
      },
      {
        version: 'E245.DV.01.01.004',
        stageList: [
          {
            id: 1,
            stageKey: '',
            stageName: '集成',
            sort: 0,
            status: StatusEnum.成功,
          },
          {
            id: 2,
            stageKey: '',
            stageName: '转测评估',
            sort: 1,
            status: StatusEnum.成功,
          },
          {
            id: 3,
            stageKey: '',
            stageName: '系统测试',
            sort: 0,
            status: StatusEnum.成功,
          },
          // {
          //   id: 4,
          //   stageKey: '',
          //   stageName: '内部发布',
          //   sort: 0,
          //   status: StatusEnum.成功,
          // },
          // {
          //   id: 5,
          //   stageKey: '',
          //   stageName: '外部发布',
          //   sort: 0,
          //   status: StatusEnum.成功,
          // },
        ],
      },
    ],
    psvplanId: 0,
  },
  {
    pSVPlanId: 1,
    cooldevProjectId: 0,
    projectSureStageId: 'E245.DV',
    planVersion: 'E245.DV.01.02',
    planStageList: [
      {
        stageName: '开发',
        sort: 0,
        status: StatusEnum.成功,
        startTime: '',
        endTime: '',
      },
      {
        stageName: '集成',
        sort: 1,
        status: StatusEnum.成功,
        startTime: '',
        endTime: '',
      },
      {
        stageName: '版本验证',
        sort: 2,
        status: StatusEnum.成功,
        startTime: '',
        endTime: '',
      },
      // {
      //   stageName: '版本发布',
      //   sort: 3,
      //   status: StatusEnum.成功,
      //   startTime: '',
      //   endTime: '',
      // },
    ],
    planCompileList: [
      // {
      //   version: 'E245.DV.01.01.001',
      //   stageList: [
      //     {
      //       id: 1,
      //       stageKey: '',
      //       stageName: '集成',
      //       sort: 0,
      //       status: StatusEnum.成功,
      //     },
      //     {
      //       id: 2,
      //       stageKey: '',
      //       stageName: '转测评估',
      //       sort: 1,
      //       status: StatusEnum.成功,
      //     },
      //     {
      //       id: 3,
      //       stageKey: '',
      //       stageName: '系统测试',
      //       sort: 0,
      //       status: StatusEnum.成功,
      //     },
      //     // {
      //     //   id: 4,
      //     //   stageKey: '',
      //     //   stageName: '内部发布',
      //     //   sort: 0,
      //     //   status: StatusEnum.成功,
      //     // },
      //     // {
      //     //   id: 5,
      //     //   stageKey: '',
      //     //   stageName: '外部发布',
      //     //   sort: 0,
      //     //   status: StatusEnum.成功,
      //     // },
      //   ],
      // },
    ],
    psvplanId: 0,
  },
  {
    pSVPlanId: 3,
    cooldevProjectId: 0,
    projectSureStageId: 'E245.DV',
    planVersion: 'E245.DV.01.03',
    planStageList: [
      {
        stageName: '开发',
        sort: 0,
        status: StatusEnum.成功,
        startTime: '',
        endTime: '',
      },
      {
        stageName: '集成',
        sort: 1,
        status: StatusEnum.成功,
        startTime: '',
        endTime: '',
      },
      {
        stageName: '版本验证',
        sort: 2,
        status: StatusEnum.成功,
        startTime: '',
        endTime: '',
      },
      // {
      //   stageName: '版本发布',
      //   sort: 3,
      //   status: StatusEnum.成功,
      //   startTime: '',
      //   endTime: '',
      // },
    ],
    planCompileList: [
      {
        version: 'E245.DV.01.01.001',
        stageList: [
          {
            id: 1,
            stageKey: '',
            stageName: '集成',
            sort: 0,
            status: StatusEnum.成功,
          },
          {
            id: 2,
            stageKey: '',
            stageName: '转测评估',
            sort: 1,
            status: StatusEnum.成功,
          },
          {
            id: 3,
            stageKey: '',
            stageName: '系统测试',
            sort: 0,
            status: StatusEnum.成功,
          },
          // {
          //   id: 4,
          //   stageKey: '',
          //   stageName: '内部发布',
          //   sort: 0,
          //   status: StatusEnum.成功,
          // },
          // {
          //   id: 5,
          //   stageKey: '',
          //   stageName: '外部发布',
          //   sort: 0,
          //   status: StatusEnum.成功,
          // },
        ],
      },
    ],
    psvplanId: 0,
  },
];
